export const contactItems = [
  {
    name: "e-mail",
    isLink: true,
    isMail: true,
    link: "mailto:supinski.dev@gmail.com",
    text: "supinski.dev@gmail.com",
    tabIndex: 11,
  },
  {
    name: "phone",
    isLink: false,
    isMail: false,
    link: "",
    text: "(+44) 07949694746",
  },
  {
    name: "linkedin",
    isLink: true,
    isMail: false,
    link: "https://www.linkedin.com/in/dominik-supi%C5%84ski-094ba3210/",
    text: "dominik-supinski",
    tabIndex: 12,
  },
  {
    name: "github",
    isLink: true,
    isMail: false,
    link: "https://www.github.com/asztonski/",
    text: "asztonski",
    tabIndex: 13,
  },
];

export const formItems = [
  {
    label: "name lastname",
    type: "text",
    name: "name",
    id: "name",
    isMultiline: false,
    rows: "",
    maxRows: "",
    helperText: "Please provide correct name and surname",
    tabIndex: "14",
  },
  {
    label: "e-mail",
    type: "email",
    name: "email",
    id: "email",
    isMultiline: false,
    rows: "",
    maxRows: "",
    helperText: "Please provide correct e-mail address",
    tabIndex: "15",
  },
  {
    label: "message",
    type: "text",
    name: "message",
    id: "message",
    isMultiline: true,
    rows: 4,
    maxRows: 16,
    helperText: "Ohh C'mon! Message is way too short.",
    tabIndex: "16",
  },
];
